baseURL = "https://blog.fuentedederecho.com.ar/"
title = "Provisorio"
theme = "hextra"
languageCode = "es"
defaultContentLanguage = "es"
enableRobotsTXT = true

[markup.goldmark.renderer]
  unsafe = true
