baseURL = "https://blog.fuentedederecho.com.ar/"
languageCode = "es"
title = "Fuente de Derecho"
theme = "hextra"

[menu]

  [[menu.main]]
    name = "Doctrina"
    url = "/doctrina/"
    weight = 1

  [[menu.main]]
    name = "Jurisprudencia"
    url = "/jurisprudencia/"
    weight = 2

  [[menu.main]]
    name = "Ley"
    url = "/ley/"
    weight = 3

  [[menu.main]]
    name = "Novedades"
    url = "/novedades/"
    weight = 4
