baseURL = "https://blog.fuentedederecho.com.ar/"
title = "Provisorio"
theme = "hextra"
languageCode = "es"
defaultContentLanguage = "es"

[params]
  description = "Sitio de pruebas con Hugo y el tema Hextra"
  author = "Fuente de Derecho"
