baseURL = "https://blog.fuentedederecho.com.ar/"
title = "Provisorio"
theme = "hextra"
languageCode = "es"
defaultContentLanguage = "es"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
