name: Deploy Hugo Site

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
          extended: true
      - name: Build
        run: |
          # Crear archivos críticos
          mkdir -p static
          echo "/*  Content-Type: text/html" > static/_headers
          touch .nojekyll
          
          # Compilar sitio
          hugo --minify --baseURL "https://blog.fuentedederecho.com.ar/"
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: blog.fuentedederecho.com.ar
